# COMPLETE PROJECT FLOW
- Dataset
-   ↓
- EDA
-   ↓
- Data Cleaning
-   ↓
- Feature Engineering
-   ↓
- Encoding
-   ↓
- Scaling
-   ↓
- Train-Test Split
-   ↓
- KNN Model
-   ↓
- Model Evaluation
-   ↓
- Save Model
-   ↓
- Streamlit Deployment

## IMPORT LIBRARIES

In [1]:
import numpy as np
import pandas as pd
import sklearn

## Load Dataset

In [2]:
df=pd.read_csv("hr.csv")
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [3]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

## EDA

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   object
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   object
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), object(9)
memory usage: 402.1+ KB

In [5]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1465    False
1466    False
1467    False
1468    False
1469    False
Length: 1470, dtype: bool

In [36]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Attrition'] = le.fit_transform(df['Attrition'])

In [38]:
x = df.drop('Attrition', axis=1)
y = df['Attrition']

In [39]:
x = x.drop(columns=[
    'EmployeeCount',
    'EmployeeNumber',
    'Over18',
    'StandardHours'
])

## **STEP 1** *DIVIDING THE DATA INTO INPUT AND OUTPUT*

In [6]:
x=df.drop(['Attrition'],axis=1)

In [7]:
x

,Age,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,2,...,1,80,0,8,0,1,6,4,0,5
1,49,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,3,...,4,80,1,10,3,3,10,7,1,7
2,37,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,4,...,2,80,0,7,3,3,0,0,0,0
3,33,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,4,...,3,80,0,8,3,3,8,7,3,0
4,27,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,1,...,4,80,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,Travel_Frequently,884,Research & Development,23,2,Medical,1,2061,3,...,3,80,1,17,3,3,5,2,0,3
1466,39,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062,4,...,1,80,1,9,5,3,7,7,1,7
1467,27,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064,2,...,2,80,1,6,0,3,6,2,0,3
1468,49,Travel_Frequently,1023,Sales,2,3,Medical,1,2065,4,...,4,80,0,17,3,2,9,6,0,8
1469,34,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068,2,...,1,80,0,6,3,4,4,3,1,2

In [9]:
y=df[['Attrition']]

In [10]:
y

     Attrition
0          Yes
1           No
2          Yes
3           No
4           No
...        ...
1465        No
1466        No
1467        No
1468        No
1469        No

[1470 rows x 1 columns]

## **STEP 2** *SPLIT THE DATA INTO TRAIN AND TEST*

In [40]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x,y,train_size=0.8,random_state=3)

In [12]:
x_train

,Age,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
1133,43,Travel_Rarely,990,Research & Development,27,3,Technical Degree,1,1599,4,...,3,80,1,8,0,3,6,4,0,2
58,31,Travel_Rarely,655,Research & Development,7,4,Life Sciences,1,76,4,...,4,80,1,10,3,2,7,7,1,7
1459,29,Travel_Rarely,1378,Research & Development,13,2,Other,1,2053,4,...,1,80,1,10,2,3,4,3,0,3
48,46,Travel_Frequently,1211,Sales,5,4,Marketing,1,62,1,...,3,80,0,14,4,3,9,6,0,8
1333,46,Travel_Rarely,1254,Sales,10,3,Life Sciences,1,1869,3,...,3,80,3,14,2,3,8,7,0,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
789,44,Travel_Rarely,1376,Human Resources,1,2,Medical,1,1098,2,...,4,80,1,24,1,3,20,6,3,6
256,42,Travel_Rarely,269,Research & Development,2,3,Medical,1,351,4,...,3,80,1,10,4,3,9,6,7,8
968,36,Travel_Frequently,607,Sales,7,3,Marketing,1,1362,1,...,4,80,1,17,2,2,15,7,6,13
952,31,Travel_Frequently,1060,Sales,1,3,Life Sciences,1,1331,4,...,1,80,0,3,2,4,3,2,2,2
1273,22,Travel_Rarely,1294,Research & Development,8,1,Medical,1,1783,3,...,3,80,0,1,6,3,1,0,0,0

In [41]:
x_train.reset_index(inplace=True)
x_train

,index,Age,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,...,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,1133,43,Travel_Rarely,990,Research & Development,27,3,Technical Degree,4,Male,...,3,3,1,8,0,3,6,4,0,2
1,58,31,Travel_Rarely,655,Research & Development,7,4,Life Sciences,4,Male,...,4,4,1,10,3,2,7,7,1,7
2,1459,29,Travel_Rarely,1378,Research & Development,13,2,Other,4,Male,...,3,1,1,10,2,3,4,3,0,3
3,48,46,Travel_Frequently,1211,Sales,5,4,Marketing,1,Male,...,4,3,0,14,4,3,9,6,0,8
4,1333,46,Travel_Rarely,1254,Sales,10,3,Life Sciences,3,Female,...,4,3,3,14,2,3,8,7,0,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1171,789,44,Travel_Rarely,1376,Human Resources,1,2,Medical,2,Male,...,3,4,1,24,1,3,20,6,3,6
1172,256,42,Travel_Rarely,269,Research & Development,2,3,Medical,4,Female,...,3,3,1,10,4,3,9,6,7,8
1173,968,36,Travel_Frequently,607,Sales,7,3,Marketing,1,Female,...,3,4,1,17,2,2,15,7,6,13
1174,952,31,Travel_Frequently,1060,Sales,1,3,Life Sciences,4,Female,...,3,1,0,3,2,4,3,2,2,2
1175,1273,22,Travel_Rarely,1294,Research & Development,8,1,Medical,3,Female,...,3,3,0,1,6,3,1,0,0,0

In [42]:
x_test.reset_index(inplace=True)
x_test

,index,Age,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,...,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,667,41,Travel_Rarely,1085,Research & Development,2,4,Life Sciences,2,Female,...,3,3,1,10,1,2,7,7,1,0
1,1166,48,Travel_Frequently,365,Research & Development,4,5,Medical,3,Male,...,4,2,1,23,3,3,2,2,2,2
2,799,42,Travel_Rarely,469,Research & Development,2,2,Medical,4,Male,...,3,4,1,23,3,3,22,6,13,7
3,1388,32,Non-Travel,1146,Research & Development,15,4,Medical,3,Female,...,3,2,1,9,6,3,5,1,1,2
4,620,35,Travel_Rarely,1343,Research & Development,27,1,Medical,3,Female,...,3,4,0,6,3,2,6,5,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
289,355,26,Travel_Rarely,933,Sales,1,3,Life Sciences,3,Male,...,3,2,1,8,3,3,8,7,7,7
290,1267,34,Non-Travel,1375,Sales,10,3,Life Sciences,4,Male,...,3,3,1,15,3,3,15,14,0,7
291,51,28,Travel_Rarely,1434,Research & Development,5,4,Technical Degree,3,Male,...,3,3,0,2,3,2,2,2,2,2
292,712,33,Travel_Rarely,461,Research & Development,13,1,Life Sciences,2,Female,...,3,1,0,5,4,3,3,2,0,2
293,578,38,Travel_Frequently,240,Research & Development,2,4,Life Sciences,1,Female,...,3,4,0,17,2,3,15,7,4,12

In [44]:
y_train

1133    0
58      0
1459    0
48      0
1333    1
       ..
789     1
256     0
968     0
952     1
1273    1
Name: Attrition, Length: 1176, dtype: int64

In [48]:
y_test

667     1
1166    0
799     0
1388    0
620     0
       ..
355     0
1267    0
51      1
712     0
578     0
Name: Attrition, Length: 294, dtype: int64

## **STEP 3** *FEATURE ENGINEERING ON TRAINING DATA*

In [49]:
cat_df=x_train.select_dtypes(include='object')
cat_df

,BusinessTravel,Department,EducationField,Gender,JobRole,MaritalStatus,OverTime
0,Travel_Rarely,Research & Development,Technical Degree,Male,Laboratory Technician,Divorced,No
1,Travel_Rarely,Research & Development,Life Sciences,Male,Laboratory Technician,Divorced,No
2,Travel_Rarely,Research & Development,Other,Male,Laboratory Technician,Married,Yes
3,Travel_Frequently,Sales,Marketing,Male,Sales Executive,Single,Yes
4,Travel_Rarely,Sales,Life Sciences,Female,Sales Executive,Married,No
...,...,...,...,...,...,...,...
1171,Travel_Rarely,Human Resources,Medical,Male,Human Resources,Married,No
1172,Travel_Rarely,Research & Development,Medical,Female,Laboratory Technician,Divorced,Yes
1173,Travel_Frequently,Sales,Marketing,Female,Sales Executive,Married,No
1174,Travel_Frequently,Sales,Life Sciences,Female,Sales Representative,Single,Yes
1175,Travel_Rarely,Research & Development,Medical,Female,Laboratory Technician,Married,Yes

In [50]:
from sklearn.preprocessing import OneHotEncoder
OHE=OneHotEncoder(sparse_output=False).set_output(transform='pandas')
cat_df_trans=OHE.fit_transform(cat_df)

In [51]:
cat_df_trans

,BusinessTravel_Non-Travel,BusinessTravel_Travel_Frequently,BusinessTravel_Travel_Rarely,Department_Human Resources,Department_Research & Development,Department_Sales,EducationField_Human Resources,EducationField_Life Sciences,EducationField_Marketing,EducationField_Medical,...,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,OverTime_No,OverTime_Yes
0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
1,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
2,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
3,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
4,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1171,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
1172,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
1173,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
1174,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
1175,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0

In [52]:
OHE.categories_

[array(['Non-Travel', 'Travel_Frequently', 'Travel_Rarely'], dtype=object),
 array(['Human Resources', 'Research & Development', 'Sales'], dtype=object),
 array(['Human Resources', 'Life Sciences', 'Marketing', 'Medical',
        'Other', 'Technical Degree'], dtype=object),
 array(['Female', 'Male'], dtype=object),
 array(['Healthcare Representative', 'Human Resources',
        'Laboratory Technician', 'Manager', 'Manufacturing Director',
        'Research Director', 'Research Scientist', 'Sales Executive',
        'Sales Representative'], dtype=object),
 array(['Divorced', 'Married', 'Single'], dtype=object),
 array(['No', 'Yes'], dtype=object)]

In [53]:
num_df = x_train[['Age', 'DailyRate', 'DistanceFromHome', 'Education', 'EnvironmentSatisfaction', 'HourlyRate', 'JobInvolvement', 'JobLevel', 'JobSatisfaction', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked', 'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction', 'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion', 'YearsWithCurrManager']]
num_df

,Age,DailyRate,DistanceFromHome,Education,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,...,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,43,990,27,3,4,87,4,1,2,4876,...,3,3,1,8,0,3,6,4,0,2
1,31,655,7,4,4,48,3,2,4,5915,...,4,4,1,10,3,2,7,7,1,7
2,29,1378,13,2,4,46,2,2,2,4025,...,3,1,1,10,2,3,4,3,0,3
3,46,1211,5,4,1,98,3,2,4,5772,...,4,3,0,14,4,3,9,6,0,8
4,46,1254,10,3,3,64,3,3,2,7314,...,4,3,3,14,2,3,8,7,0,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1171,44,1376,1,2,2,91,2,3,1,10482,...,3,4,1,24,1,3,20,6,3,6
1172,42,269,2,3,4,56,2,1,1,2593,...,3,3,1,10,4,3,9,6,7,8
1173,36,607,7,3,1,83,4,2,1,4639,...,3,4,1,17,2,2,15,7,6,13
1174,31,1060,1,3,4,54,3,1,2,2302,...,3,1,0,3,2,4,3,2,2,2
1175,22,1294,8,1,3,79,3,1,1,2398,...,3,3,0,1,6,3,1,0,0,0

In [54]:
no_trans = x_train[['PerformanceRating', 'StockOptionLevel']]
no_trans

      PerformanceRating  StockOptionLevel
0                     3                 1
1                     4                 1
2                     3                 1
3                     4                 0
4                     4                 3
...                 ...               ...
1171                  3                 1
1172                  3                 1
1173                  3                 1
1174                  3                 0
1175                  3                 0

[1176 rows x 2 columns]

In [55]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler().set_output(transform='pandas')
num_df_trans=scaler.fit_transform(num_df)

In [56]:
num_df_trans

,Age,DailyRate,DistanceFromHome,Education,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,...,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,0.595238,0.636103,0.928571,0.50,1.000000,0.814286,1.000000,0.00,0.333333,0.203633,...,0.0,0.666667,0.333333,0.200,0.000000,0.666667,0.150,0.222222,0.000000,0.117647
1,0.309524,0.396132,0.214286,0.75,1.000000,0.257143,0.666667,0.25,1.000000,0.258346,...,1.0,1.000000,0.333333,0.250,0.500000,0.333333,0.175,0.388889,0.066667,0.411765
2,0.261905,0.914040,0.428571,0.25,1.000000,0.228571,0.333333,0.25,0.333333,0.158820,...,0.0,0.000000,0.333333,0.250,0.333333,0.666667,0.100,0.166667,0.000000,0.176471
3,0.666667,0.794413,0.142857,0.75,0.000000,0.971429,0.666667,0.25,1.000000,0.250816,...,1.0,0.666667,0.000000,0.350,0.666667,0.666667,0.225,0.333333,0.000000,0.470588
4,0.666667,0.825215,0.321429,0.50,0.666667,0.485714,0.666667,0.50,0.333333,0.332017,...,1.0,0.666667,1.000000,0.350,0.333333,0.666667,0.200,0.388889,0.000000,0.411765
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1171,0.619048,0.912607,0.000000,0.25,0.333333,0.871429,0.333333,0.50,0.000000,0.498841,...,0.0,1.000000,0.333333,0.600,0.166667,0.666667,0.500,0.333333,0.200000,0.352941
1172,0.571429,0.119628,0.035714,0.50,1.000000,0.371429,0.333333,0.00,0.000000,0.083412,...,0.0,0.666667,0.333333,0.250,0.666667,0.666667,0.225,0.333333,0.466667,0.470588
1173,0.428571,0.361748,0.214286,0.50,0.000000,0.757143,1.000000,0.25,0.000000,0.191153,...,0.0,1.000000,0.333333,0.425,0.333333,0.333333,0.375,0.388889,0.400000,0.764706
1174,0.309524,0.686246,0.000000,0.50,1.000000,0.342857,0.666667,0.00,0.333333,0.068088,...,0.0,0.000000,0.000000,0.075,0.333333,1.000000,0.075,0.111111,0.133333,0.117647
1175,0.095238,0.853868,0.250000,0.00,0.666667,0.700000,0.666667,0.00,0.000000,0.073144,...,0.0,0.666667,0.000000,0.025,1.000000,0.666667,0.025,0.000000,0.000000,0.000000

In [57]:
num_df_trans.reset_index(inplace=True)

In [58]:
cat_df_trans.reset_index(inplace=True)

In [59]:
no_trans.reset_index(inplace=True)

In [60]:
x_train_trans=pd.concat([num_df_trans, cat_df_trans, no_trans], axis=1)

In [61]:
x_train_trans

,index,Age,DailyRate,DistanceFromHome,Education,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,...,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,OverTime_No,OverTime_Yes,index,PerformanceRating,StockOptionLevel
0,0,0.595238,0.636103,0.928571,0.50,1.000000,0.814286,1.000000,0.00,0.333333,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0,3,1
1,1,0.309524,0.396132,0.214286,0.75,1.000000,0.257143,0.666667,0.25,1.000000,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1,4,1
2,2,0.261905,0.914040,0.428571,0.25,1.000000,0.228571,0.333333,0.25,0.333333,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,2,3,1
3,3,0.666667,0.794413,0.142857,0.75,0.000000,0.971429,0.666667,0.25,1.000000,...,1.0,0.0,0.0,0.0,1.0,0.0,1.0,3,4,0
4,4,0.666667,0.825215,0.321429,0.50,0.666667,0.485714,0.666667,0.50,0.333333,...,1.0,0.0,0.0,1.0,0.0,1.0,0.0,4,4,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1171,1171,0.619048,0.912607,0.000000,0.25,0.333333,0.871429,0.333333,0.50,0.000000,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1171,3,1
1172,1172,0.571429,0.119628,0.035714,0.50,1.000000,0.371429,0.333333,0.00,0.000000,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1172,3,1
1173,1173,0.428571,0.361748,0.214286,0.50,0.000000,0.757143,1.000000,0.25,0.000000,...,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1173,3,1
1174,1174,0.309524,0.686246,0.000000,0.50,1.000000,0.342857,0.666667,0.00,0.333333,...,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1174,3,0
1175,1175,0.095238,0.853868,0.250000,0.00,0.666667,0.700000,0.666667,0.00,0.000000,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1175,3,0

In [62]:
x_train_trans.pop('index')

      index  index  index
0         0      0      0
1         1      1      1
2         2      2      2
3         3      3      3
4         4      4      4
...     ...    ...    ...
1171   1171   1171   1171
1172   1172   1172   1172
1173   1173   1173   1173
1174   1174   1174   1174
1175   1175   1175   1175

[1176 rows x 3 columns]

In [63]:
x_train_trans

,Age,DailyRate,DistanceFromHome,Education,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,...,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,OverTime_No,OverTime_Yes,PerformanceRating,StockOptionLevel
0,0.595238,0.636103,0.928571,0.50,1.000000,0.814286,1.000000,0.00,0.333333,0.203633,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,3,1
1,0.309524,0.396132,0.214286,0.75,1.000000,0.257143,0.666667,0.25,1.000000,0.258346,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,4,1
2,0.261905,0.914040,0.428571,0.25,1.000000,0.228571,0.333333,0.25,0.333333,0.158820,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,3,1
3,0.666667,0.794413,0.142857,0.75,0.000000,0.971429,0.666667,0.25,1.000000,0.250816,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,4,0
4,0.666667,0.825215,0.321429,0.50,0.666667,0.485714,0.666667,0.50,0.333333,0.332017,...,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,4,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1171,0.619048,0.912607,0.000000,0.25,0.333333,0.871429,0.333333,0.50,0.000000,0.498841,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,3,1
1172,0.571429,0.119628,0.035714,0.50,1.000000,0.371429,0.333333,0.00,0.000000,0.083412,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,3,1
1173,0.428571,0.361748,0.214286,0.50,0.000000,0.757143,1.000000,0.25,0.000000,0.191153,...,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,3,1
1174,0.309524,0.686246,0.000000,0.50,1.000000,0.342857,0.666667,0.00,0.333333,0.068088,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,3,0
1175,0.095238,0.853868,0.250000,0.00,0.666667,0.700000,0.666667,0.00,0.000000,0.073144,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,3,0

## **STEP 4** *TRAINING MODEL USING ALGORITHM*

In [66]:
from sklearn.neighbors import KNeighborsClassifier

model=KNeighborsClassifier()
# x_train_trans=df.drop(['Gender'],axis=1)
model.fit(x_train_trans, y_train)

KNeighborsClassifier()

## step5 - *Feature Transformations on Test Data*

In [67]:
x_test

,index,Age,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,...,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,667,41,Travel_Rarely,1085,Research & Development,2,4,Life Sciences,2,Female,...,3,3,1,10,1,2,7,7,1,0
1,1166,48,Travel_Frequently,365,Research & Development,4,5,Medical,3,Male,...,4,2,1,23,3,3,2,2,2,2
2,799,42,Travel_Rarely,469,Research & Development,2,2,Medical,4,Male,...,3,4,1,23,3,3,22,6,13,7
3,1388,32,Non-Travel,1146,Research & Development,15,4,Medical,3,Female,...,3,2,1,9,6,3,5,1,1,2
4,620,35,Travel_Rarely,1343,Research & Development,27,1,Medical,3,Female,...,3,4,0,6,3,2,6,5,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
289,355,26,Travel_Rarely,933,Sales,1,3,Life Sciences,3,Male,...,3,2,1,8,3,3,8,7,7,7
290,1267,34,Non-Travel,1375,Sales,10,3,Life Sciences,4,Male,...,3,3,1,15,3,3,15,14,0,7
291,51,28,Travel_Rarely,1434,Research & Development,5,4,Technical Degree,3,Male,...,3,3,0,2,3,2,2,2,2,2
292,712,33,Travel_Rarely,461,Research & Development,13,1,Life Sciences,2,Female,...,3,1,0,5,4,3,3,2,0,2
293,578,38,Travel_Frequently,240,Research & Development,2,4,Life Sciences,1,Female,...,3,4,0,17,2,3,15,7,4,12

In [69]:
num_df=x_test[['Age', 'DailyRate', 'DistanceFromHome', 'Education', 'EnvironmentSatisfaction', 'HourlyRate', 'JobInvolvement', 'JobLevel', 'JobSatisfaction', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked', 'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction', 'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion', 'YearsWithCurrManager']]
num_df

,Age,DailyRate,DistanceFromHome,Education,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,...,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,1085,2,4,2,57,1,1,4,2778,...,3,3,1,10,1,2,7,7,1,0
1,48,365,4,5,3,89,2,4,4,15202,...,4,2,1,23,3,3,2,2,2,2
2,42,469,2,2,4,35,3,4,1,17665,...,3,4,1,23,3,3,22,6,13,7
3,32,1146,15,4,3,34,3,2,4,6667,...,3,2,1,9,6,3,5,1,1,2
4,35,1343,27,1,3,53,2,1,1,2559,...,3,4,0,6,3,2,6,5,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
289,26,933,1,3,3,57,3,2,3,5296,...,3,2,1,8,3,3,8,7,7,7
290,34,1375,10,3,4,87,3,2,3,4001,...,3,3,1,15,3,3,15,14,0,7
291,28,1434,5,4,3,50,3,1,3,3441,...,3,3,0,2,3,2,2,2,2,2
292,33,461,13,1,2,53,3,1,4,3452,...,3,1,0,5,4,3,3,2,0,2
293,38,240,2,4,1,75,4,2,1,5980,...,3,4,0,17,2,3,15,7,4,12

In [70]:
cat_df = x_test.select_dtypes(include='object')

In [71]:
no_trans= x_test[['PerformanceRating', 'StockOptionLevel']]

In [72]:
# num trans
num_df_trans=scaler.transform(num_df)
num_df_trans

,Age,DailyRate,DistanceFromHome,Education,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,...,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,0.547619,0.704155,0.035714,0.75,0.333333,0.385714,0.000000,0.00,1.000000,0.093154,...,0.0,0.666667,0.333333,0.250,0.166667,0.333333,0.175,0.388889,0.066667,0.000000
1,0.714286,0.188395,0.107143,1.00,0.666667,0.842857,0.333333,0.75,1.000000,0.747393,...,1.0,0.333333,0.333333,0.575,0.500000,0.666667,0.050,0.111111,0.133333,0.117647
2,0.571429,0.262894,0.035714,0.25,1.000000,0.071429,0.666667,0.75,0.000000,0.877093,...,0.0,1.000000,0.333333,0.575,0.500000,0.666667,0.550,0.333333,0.866667,0.411765
3,0.333333,0.747851,0.500000,0.75,0.666667,0.057143,0.666667,0.25,1.000000,0.297946,...,0.0,0.333333,0.333333,0.225,1.000000,0.666667,0.125,0.055556,0.066667,0.117647
4,0.404762,0.888968,0.928571,0.00,0.666667,0.328571,0.333333,0.00,0.000000,0.081622,...,0.0,1.000000,0.000000,0.150,0.500000,0.333333,0.150,0.277778,0.066667,0.058824
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
289,0.190476,0.595272,0.000000,0.50,0.666667,0.385714,0.666667,0.25,0.666667,0.225750,...,0.0,0.333333,0.333333,0.200,0.500000,0.666667,0.200,0.388889,0.466667,0.411765
290,0.380952,0.911891,0.321429,0.50,1.000000,0.814286,0.666667,0.25,0.666667,0.157557,...,0.0,0.666667,0.333333,0.375,0.500000,0.666667,0.375,0.777778,0.000000,0.411765
291,0.238095,0.954155,0.142857,0.75,0.666667,0.285714,0.666667,0.00,0.666667,0.128067,...,0.0,0.666667,0.000000,0.050,0.500000,0.333333,0.050,0.111111,0.133333,0.117647
292,0.357143,0.257163,0.428571,0.00,0.333333,0.328571,0.666667,0.00,1.000000,0.128647,...,0.0,0.000000,0.000000,0.125,0.666667,0.666667,0.075,0.111111,0.000000,0.117647
293,0.476190,0.098854,0.035714,0.75,0.000000,0.642857,1.000000,0.25,0.000000,0.261769,...,0.0,1.000000,0.000000,0.425,0.333333,0.666667,0.375,0.388889,0.266667,0.705882

In [73]:
# cat df transformation

cat_df_trans=OHE.transform(cat_df)
cat_df_trans

,BusinessTravel_Non-Travel,BusinessTravel_Travel_Frequently,BusinessTravel_Travel_Rarely,Department_Human Resources,Department_Research & Development,Department_Sales,EducationField_Human Resources,EducationField_Life Sciences,EducationField_Marketing,EducationField_Medical,...,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,OverTime_No,OverTime_Yes
0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
1,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
2,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
3,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
4,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
289,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
290,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
291,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
292,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
293,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0

In [74]:
num_df_trans.reset_index(inplace=True)

In [75]:
cat_df_trans.reset_index(inplace=True)

In [76]:
no_trans.reset_index(inplace=True)

In [77]:
x_test_trans=pd.concat([num_df_trans, cat_df_trans, no_trans],axis=1)

In [78]:
x_test_trans.pop('index')

     index  index  index
0        0      0      0
1        1      1      1
2        2      2      2
3        3      3      3
4        4      4      4
..     ...    ...    ...
289    289    289    289
290    290    290    290
291    291    291    291
292    292    292    292
293    293    293    293

[294 rows x 3 columns]

In [79]:
x_test_trans

,Age,DailyRate,DistanceFromHome,Education,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,...,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,OverTime_No,OverTime_Yes,PerformanceRating,StockOptionLevel
0,0.547619,0.704155,0.035714,0.75,0.333333,0.385714,0.000000,0.00,1.000000,0.093154,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,3,1
1,0.714286,0.188395,0.107143,1.00,0.666667,0.842857,0.333333,0.75,1.000000,0.747393,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,4,1
2,0.571429,0.262894,0.035714,0.25,1.000000,0.071429,0.666667,0.75,0.000000,0.877093,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,3,1
3,0.333333,0.747851,0.500000,0.75,0.666667,0.057143,0.666667,0.25,1.000000,0.297946,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,3,1
4,0.404762,0.888968,0.928571,0.00,0.666667,0.328571,0.333333,0.00,0.000000,0.081622,...,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
289,0.190476,0.595272,0.000000,0.50,0.666667,0.385714,0.666667,0.25,0.666667,0.225750,...,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,3,1
290,0.380952,0.911891,0.321429,0.50,1.000000,0.814286,0.666667,0.25,0.666667,0.157557,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,3,1
291,0.238095,0.954155,0.142857,0.75,0.666667,0.285714,0.666667,0.00,0.666667,0.128067,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,3,0
292,0.357143,0.257163,0.428571,0.00,0.333333,0.328571,0.666667,0.00,1.000000,0.128647,...,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,3,0
293,0.476190,0.098854,0.035714,0.75,0.000000,0.642857,1.000000,0.25,0.000000,0.261769,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,3,0

## step6 - *Predicting on x_test_Trans*

In [81]:
y_pred=model.predict(x_test_trans)

In [82]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0])

## step7 - passing y_test(actual) and y_pred(model_prediction) to evaluation metrics

In [83]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.8707482993197279

In [88]:
import joblib

joblib.dump({'model': model, 'cat_encod': OHE, 'num_encod': scaler},'hr.pkl')

['hr.pkl']

In [89]:
prod_files = joblib.load('hr.pkl')

In [90]:
prod_files['model']

KNeighborsClassifier()

In [91]:
prod_files['cat_encod']

OneHotEncoder(sparse_output=False)

In [92]:
prod_files['num_encod']

MinMaxScaler()

# Business Deliverables

## *I built a reusable HR employee attrition prediction pipeline using scikit-learn. The pipeline preprocesses the employee data by handling missing values, encoding categorical features, and scaling numerical features. The preprocessed data is saved as hr.pkl to ensure the same transformations are applied to new data. The pipeline then trains a machine learning model, evaluates its performance using appropriate metrics, and saves the trained model for future predictions. This workflow can be reused to predict whether a new employee is likely to leave the organization without manually repeating the preprocessing and model training steps.*